package enum

type UTMModule string

const (
	FILE_INTEGRITY     UTMModule = "FILE_INTEGRITY"
	VULNERABILITIES              = "VULNERABILITIES"
	ASSET_SCANNER                = "ASSET_SCANNER"
	AD_AUDIT                     = "AD_AUDIT"
	NETFLOW                      = "NETFLOW"
	WINDOWS_AGENT                = "WINDOWS_AGENT"
	SYSLOG                       = "SYSLOG"
	LINUX_LOGS                   = "LINUX_LOGS"
	VMWARE                       = "VMWARE"
	WEBROOT                      = "WEBROOT"
	AWS_TRAFFIC_MIRROR           = "AWS_TRAFFIC_MIRROR"
	AWS_IAM_USER                 = "AWS_IAM_USER"
	AWS_CLOUDTRAIL               = "AWS_CLOUDTRAIL"
	AWS_SQL_SERVER               = "AWS_SQL_SERVER"
	AWS_POSTGRESQL               = "AWS_POSTGRESQL"
	AWS_BEANSTALK                = "AWS_BEANSTALK"
	AWS_FARGATE                  = "AWS_FARGATE"
	AWS_LAMBDA                   = "AWS_LAMBDA"
	SOPHOS                       = "SOPHOS"
	AZURE                        = "AZURE"
	O365                         = "O365"
	IIS                          = "IIS"
	GCP                          = "GCP"
	JSON                         = "JSON"
	MACOS_AGENT                  = "MACOS_AGENT"
	LINUX_AGENT                  = "LINUX_AGENT"
	APACHE                       = "APACHE"
	APACHE2                      = "APACHE2"
	AUDITD                       = "AUDITD"
	ELASTICSEARCH                = "ELASTICSEARCH"
	HAPROXY                      = "HAPROXY"
	ICINGA                       = "ICINGA"
	KAFKA                        = "KAFKA"
	KIBAN                        = "KIBAN"
	LOGSTASH                     = "LOGSTASH"
	MONGODB                      = "MONGODB"
	MYSQL                        = "MYSQL"
	NATS                         = "NATS"
	NGINX                        = "NGINX"
	OSQUERY                      = "OSQUERY"
	PENSANDO                     = "PENSANDO"
	POSTGRESQL                   = "POSTGRESQL"
	REDIS                        = "REDIS"
	SANTA                        = "SANTA"
	SYSTEM                       = "SYSTEM"
	TRAEFIK                      = "TRAEFIK"
	CISCO                        = "CISCO"
	MERAKI                       = "MERAKI"
)
